language: cpp
compiler: gcc
dist: trusty

before_install:
    #ubuntu
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  #g++
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  # cppcheck
  - sudo apt-get install -qq cppcheck

script:
  - g++ app/main.cpp src/*.cpp -std=c++17 -Iinclude -o loggerCpp
  - ./loggerCpp
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 .
