language: cpp
compiler: gcc
dist: trusty

before_install:
    #ubuntu
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  #g++
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # cppcheck
  - sudo apt-get install -qq cppcheck

script: 
  - g++ SwiFTLog/src/main.cpp SwiFTLog/src/clock.cpp SwiFTLog/src/levelUtils.cpp -std=c++17 -ISwiFTLog/include -o loggerCpp
  - ./loggerCpp
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 