name: CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - name: configure
      run: cmake -DCMAKE_BUILD_TYPE=debug ..
    - name: build
      run: cmake --build build
   

  build-windows:

    runs-on: windows-latest
    
    steps:
    - name: configure
      run: |
         cmake ..
    - name: build
      run: cmake --build build
    
